name: Install PS Modules
description: Installs PowerShell modules and versions. Uses caching to increase reliability

inputs:
  modules:
    description: "Required. Multiline string. List of the modules to install. Format: <moduleName>:<version>"
    required: true

runs:
  using: composite
  steps:
    - name: Register-PSGallery
      shell: pwsh
      env:
        actionPath: ${{ github.action_path }}
        debug: ${{ runner.debug }}
      run: |
        #* Register-PSGallery

        #* Set debug preference from runner configuration
        $DebugPreference = [bool]$env:debug ? "Continue" : "SilentlyContinue"

        #* Import module
        Import-Module "$($env:actionPath)/src/InstallPSModules.psm1" -Force

        #* Register PS Gallery
        Register-PSGallery

    - name: Parse PS Modules input
      id: parse-psmodules
      shell: pwsh
      env:
        modules: ${{ inputs.modules }}
        actionPath: ${{ github.action_path }}
        debug: ${{ runner.debug }}
      run: |
        #* Parse-PSModules

        #* Set debug preference from runner configuration
        $DebugPreference = [bool]$env:debug ? "Continue" : "SilentlyContinue"

        #* Import module
        Import-Module "$($env:actionPath)/src/InstallPSModules.psm1" -Force

        #* Parse PS Modules input
        $modules = Parse-PSModules -Modules $env:modules

        #* Output module versions
        Write-Output "moduleversions=$($versionsString)" >> $env:GITHUB_OUTPUT

    - name: Install and cache PowerShell modules
      uses: potatoqualitee/psmodulecache@v6.2.1
      with:
        modules-to-cache: ${{ steps.parse-psmodules.outputs.moduleversions }}
        updatable: true
