name: Install PS Modules
description: Installs PowerShell modules and versions. Uses caching to increase reliability

inputs:
  modules:
    description: "Required. Multiline string. List of the modules to install. Format: <moduleName>:<version>"
    required: true

runs:
  using: composite
  steps:
    - name: Register-PSGallery
      shell: pwsh
      env:
        actionPath: ${{ github.action_path }}
        debug: ${{ runner.debug }}
      run: |
        #* Register-PSGallery

        #* Set debug preference from runner configuration
        $DebugPreference = [bool]$env:debug ? "Continue" : "SilentlyContinue"

        #* Import module
        Import-Module "$($env:actionPath)/src/InstallPSModules.psm1" -Force

        #* Register PS Gallery
        Register-PSGallery

    - name: Format PS Modules input
      id: format-psmodulesinput
      shell: pwsh
      env:
        modules: ${{ inputs.modules }}
        actionPath: ${{ github.action_path }}
        debug: ${{ runner.debug }}
      run: |
        #* Format-PSModulesInput

        #* Set debug preference from runner configuration
        $DebugPreference = [bool]$env:debug ? "Continue" : "SilentlyContinue"

        #* Import module
        Import-Module "$($env:actionPath)/src/InstallPSModules.psm1" -Force

        #* Format PS Modules input
        $modulesString = Format-PSModulesInput -InputString $env:modules

        #* Is updatable
        $isUpdatable = $modulesString -match '::'

        #* Output modules string
        Write-Output "modules-string=$($modulesString)" >> $env:GITHUB_OUTPUT
        Write-Output "updatable=$($isUpdatable.ToString().ToLower())" >> $env:GITHUB_OUTPUT

    - name: Install and cache PowerShell modules
      uses: potatoqualitee/psmodulecache@v6.2.1
      with:
        modules-to-cache: ${{ steps.format-psmodulesinput.outputs.modules-string }}
        updatable: ${{ steps.format-psmodulesinput.outputs.updatable }}
